/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SocietyService } from "../society.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SocietyCreateInput } from "./SocietyCreateInput";
import { SocietyWhereInput } from "./SocietyWhereInput";
import { SocietyWhereUniqueInput } from "./SocietyWhereUniqueInput";
import { SocietyFindManyArgs } from "./SocietyFindManyArgs";
import { SocietyUpdateInput } from "./SocietyUpdateInput";
import { Society } from "./Society";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SocietyControllerBase {
  constructor(
    protected readonly service: SocietyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Society })
  @nestAccessControl.UseRoles({
    resource: "Society",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: SocietyCreateInput): Promise<Society> {
    return await this.service.create({
      data: {
        ...data,

        address: {
          connect: data.address,
        },
      },
      select: {
        address: {
          select: {
            id: true,
          },
        },

        cmunname: true,
        createdAt: true,
        deleted: true,
        description: true,
        enabled: true,
        id: true,
        managerName: true,
        maxRequiredMember: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Society] })
  @ApiNestedQuery(SocietyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Society",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Society[]> {
    const args = plainToClass(SocietyFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        address: {
          select: {
            id: true,
          },
        },

        cmunname: true,
        createdAt: true,
        deleted: true,
        description: true,
        enabled: true,
        id: true,
        managerName: true,
        maxRequiredMember: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Society })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Society",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: SocietyWhereUniqueInput
  ): Promise<Society | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        address: {
          select: {
            id: true,
          },
        },

        cmunname: true,
        createdAt: true,
        deleted: true,
        description: true,
        enabled: true,
        id: true,
        managerName: true,
        maxRequiredMember: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Society })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Society",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: SocietyWhereUniqueInput,
    @common.Body() data: SocietyUpdateInput
  ): Promise<Society | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          address: {
            connect: data.address,
          },
        },
        select: {
          address: {
            select: {
              id: true,
            },
          },

          cmunname: true,
          createdAt: true,
          deleted: true,
          description: true,
          enabled: true,
          id: true,
          managerName: true,
          maxRequiredMember: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Society })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Society",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: SocietyWhereUniqueInput
  ): Promise<Society | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          address: {
            select: {
              id: true,
            },
          },

          cmunname: true,
          createdAt: true,
          deleted: true,
          description: true,
          enabled: true,
          id: true,
          managerName: true,
          maxRequiredMember: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
